### ISSUE TITLE
Boa noite

### ISSUE THREAD

**Issue by lepokoloko** [joaosouz4dev/zap-bot#1]
Eu sou entusiasta em programacao, não entendo muito bem, mas se eu entendi o script, no momento a unica função que esta funcionando seria a primeira parte, que da a boas vindas e apresenta o cardapio, correto? para continuar a conversação, ali em client.onMessage eu devo colocar IFS ou ELSES, para continuar com o atendimento ao cliente? ou estou enganado, ou continuaria o atendimento buscando pelo BD local, verificando que o cliente ja escolheu a opção do lanche ?

**Comment by joaosouz4dev** [comment]
Está enganado, controlamos o "estagio" de conversação, se a pessoa está no primeiro estagio ela recebe boas vindas, no segundo recebe o menu, terceiro... etc

**Comment by joaosouz4dev** [comment]
Posso te ajudar a fazer uma implementação como essa para qualquer ramo.
E vc também pode testar essa aplicação. iniciando o processo do node e lendo o qrcode com seu smartfone

**Comment by lepokoloko** [comment]
Bom dia, eu estou rodando uma aplicação, myzap e consigo enviar mensagem e responder mensagem, só estou com dificuldade em criar o atendimento com as opções de forma dinâmica rs, peguei seu código e criei um IF lá dentro do projeto myzap, porém só funciona a primeira parte, mas acredito que é por eu estar usando um condição, aí as demais mensagem não caem dentro de nenhum IF :) me chama no WhatsApp se puder 15 996213328

**Comment by joaosouz4dev** [comment]
ok
